project:
  type: website
  output-dir: docs

website:
  title: "Group Study"
  navbar:
    left:
      - href: index.qmd
        text: Syllabus
      - materials.qmd
      - links.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



